version = 0.1
[default.deploy.parameters]
stack_name = "ffmpeg-apm-layer"
resolve_s3 = true
s3_prefix = "ffmpeg-apm-layer"
region = "ap-southeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
